// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/task/v1/task.proto

package taskv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	ScheduledAt   int64                  `protobuf:"varint,4,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"` // Unix timestamp, 0 = immediate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskRequest) Reset() {
	*x = SubmitTaskRequest{}
	mi := &file_proto_task_v1_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskRequest) ProtoMessage() {}

func (x *SubmitTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_v1_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskRequest.ProtoReflect.Descriptor instead.
func (*SubmitTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_v1_task_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitTaskRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SubmitTaskRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SubmitTaskRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *SubmitTaskRequest) GetScheduledAt() int64 {
	if x != nil {
		return x.ScheduledAt
	}
	return 0
}

type SubmitTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskResponse) Reset() {
	*x = SubmitTaskResponse{}
	mi := &file_proto_task_v1_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskResponse) ProtoMessage() {}

func (x *SubmitTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_v1_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskResponse.ProtoReflect.Descriptor instead.
func (*SubmitTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_v1_task_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SubmitTaskResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubmitTaskResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type GetTaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskStatusRequest) Reset() {
	*x = GetTaskStatusRequest{}
	mi := &file_proto_task_v1_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskStatusRequest) ProtoMessage() {}

func (x *GetTaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_v1_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskStatusRequest.ProtoReflect.Descriptor instead.
func (*GetTaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_v1_task_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskStatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TaskStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Attempts      int32                  `protobuf:"varint,4,opt,name=attempts,proto3" json:"attempts,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt   int64                  `protobuf:"varint,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"` // 0 if not yet complete
	DurationMs    int64                  `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Error         string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"` // populated on failure
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusResponse) Reset() {
	*x = TaskStatusResponse{}
	mi := &file_proto_task_v1_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusResponse) ProtoMessage() {}

func (x *TaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_v1_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusResponse.ProtoReflect.Descriptor instead.
func (*TaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_v1_task_proto_rawDescGZIP(), []int{3}
}

func (x *TaskStatusResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskStatusResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TaskStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskStatusResponse) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *TaskStatusResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *TaskStatusResponse) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

func (x *TaskStatusResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *TaskStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BulkSubmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Submitted     int32                  `protobuf:"varint,1,opt,name=submitted,proto3" json:"submitted,omitempty"`
	Failed        int32                  `protobuf:"varint,2,opt,name=failed,proto3" json:"failed,omitempty"`
	TaskIds       []string               `protobuf:"bytes,3,rep,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkSubmitResponse) Reset() {
	*x = BulkSubmitResponse{}
	mi := &file_proto_task_v1_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkSubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkSubmitResponse) ProtoMessage() {}

func (x *BulkSubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_v1_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkSubmitResponse.ProtoReflect.Descriptor instead.
func (*BulkSubmitResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_v1_task_proto_rawDescGZIP(), []int{4}
}

func (x *BulkSubmitResponse) GetSubmitted() int32 {
	if x != nil {
		return x.Submitted
	}
	return 0
}

func (x *BulkSubmitResponse) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *BulkSubmitResponse) GetTaskIds() []string {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

var File_proto_task_v1_task_proto protoreflect.FileDescriptor

const file_proto_task_v1_task_proto_rawDesc = "" +
	"\n" +
	"\x18proto/task/v1/task.proto\x12\atask.v1\"\x80\x01\n" +
	"\x11SubmitTaskRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12!\n" +
	"\fscheduled_at\x18\x04 \x01(\x03R\vscheduledAt\"d\n" +
	"\x12SubmitTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\"/\n" +
	"\x14GetTaskStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\xee\x01\n" +
	"\x12TaskStatusResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1a\n" +
	"\battempts\x18\x04 \x01(\x05R\battempts\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12!\n" +
	"\fcompleted_at\x18\x06 \x01(\x03R\vcompletedAt\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x03R\n" +
	"durationMs\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\"e\n" +
	"\x12BulkSubmitResponse\x12\x1c\n" +
	"\tsubmitted\x18\x01 \x01(\x05R\tsubmitted\x12\x16\n" +
	"\x06failed\x18\x02 \x01(\x05R\x06failed\x12\x19\n" +
	"\btask_ids\x18\x03 \x03(\tR\ataskIds2\xc2\x02\n" +
	"\vTaskService\x12E\n" +
	"\n" +
	"SubmitTask\x12\x1a.task.v1.SubmitTaskRequest\x1a\x1b.task.v1.SubmitTaskResponse\x12K\n" +
	"\rGetTaskStatus\x12\x1d.task.v1.GetTaskStatusRequest\x1a\x1b.task.v1.TaskStatusResponse\x12Q\n" +
	"\x11StreamTaskUpdates\x12\x1d.task.v1.GetTaskStatusRequest\x1a\x1b.task.v1.TaskStatusResponse0\x01\x12L\n" +
	"\x0fBulkSubmitTasks\x12\x1a.task.v1.SubmitTaskRequest\x1a\x1b.task.v1.BulkSubmitResponse(\x01B:Z8github.com/ramiqadoumi/go-task-flow/proto/task/v1;taskv1b\x06proto3"

var (
	file_proto_task_v1_task_proto_rawDescOnce sync.Once
	file_proto_task_v1_task_proto_rawDescData []byte
)

func file_proto_task_v1_task_proto_rawDescGZIP() []byte {
	file_proto_task_v1_task_proto_rawDescOnce.Do(func() {
		file_proto_task_v1_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_task_v1_task_proto_rawDesc), len(file_proto_task_v1_task_proto_rawDesc)))
	})
	return file_proto_task_v1_task_proto_rawDescData
}

var file_proto_task_v1_task_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_task_v1_task_proto_goTypes = []any{
	(*SubmitTaskRequest)(nil),    // 0: task.v1.SubmitTaskRequest
	(*SubmitTaskResponse)(nil),   // 1: task.v1.SubmitTaskResponse
	(*GetTaskStatusRequest)(nil), // 2: task.v1.GetTaskStatusRequest
	(*TaskStatusResponse)(nil),   // 3: task.v1.TaskStatusResponse
	(*BulkSubmitResponse)(nil),   // 4: task.v1.BulkSubmitResponse
}
var file_proto_task_v1_task_proto_depIdxs = []int32{
	0, // 0: task.v1.TaskService.SubmitTask:input_type -> task.v1.SubmitTaskRequest
	2, // 1: task.v1.TaskService.GetTaskStatus:input_type -> task.v1.GetTaskStatusRequest
	2, // 2: task.v1.TaskService.StreamTaskUpdates:input_type -> task.v1.GetTaskStatusRequest
	0, // 3: task.v1.TaskService.BulkSubmitTasks:input_type -> task.v1.SubmitTaskRequest
	1, // 4: task.v1.TaskService.SubmitTask:output_type -> task.v1.SubmitTaskResponse
	3, // 5: task.v1.TaskService.GetTaskStatus:output_type -> task.v1.TaskStatusResponse
	3, // 6: task.v1.TaskService.StreamTaskUpdates:output_type -> task.v1.TaskStatusResponse
	4, // 7: task.v1.TaskService.BulkSubmitTasks:output_type -> task.v1.BulkSubmitResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_task_v1_task_proto_init() }
func file_proto_task_v1_task_proto_init() {
	if File_proto_task_v1_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_task_v1_task_proto_rawDesc), len(file_proto_task_v1_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_task_v1_task_proto_goTypes,
		DependencyIndexes: file_proto_task_v1_task_proto_depIdxs,
		MessageInfos:      file_proto_task_v1_task_proto_msgTypes,
	}.Build()
	File_proto_task_v1_task_proto = out.File
	file_proto_task_v1_task_proto_goTypes = nil
	file_proto_task_v1_task_proto_depIdxs = nil
}
